### ISSUE TITLE
Async remote method always returns null

### ISSUE THREAD

**Issue by madeleinedaly** [kiwanami/node-elrpc#2]
I'm trying to follow the instructions in the README for defining a remote method that returns a promise, but my client code (in Emacs) only ever receives null after calling that method. And that null appears to be returned synchronously, before the async task in my remote method actually resolves a real value to return.

I created a failing test case for this issue here: https://github.com/madeleinedaly/node-elrpc/commit/525b722c5fef286251f5fd1a489a80c9738f688e

**Comment by madeleinedaly** [comment]
It turns out that returning a native promise from a remote method won't pass the `instanceof` check here:
https://github.com/kiwanami/node-elrpc/blob/e5f87df1207d91e04b8daa625870467a0cfc05e2/lib/elrpc.js#L423

My test above passes if I return a bluebird promise from the remote method. I wonder if it's worth updating the docs to specify that bluebird must be used? Or we could use something like https://github.com/sindresorhus/p-is-promise instead of `instanceof` to allow either native or bluebird promises in the caller. I'd be happy to contribute the latter change as a PR.

**Comment by kiwanami** [comment]
Thank you for your nice report. I merged your PR.

Yes. I also think that this project should remove bluebird as a polyfill of ES6 Promise...

**Comment by madeleinedaly** [comment]
Thanks for this set of libraries! It has opened a new world of possibilities for me.
